import React, { useRef, useState } from 'react';
import { Download, Upload, ChevronRight, Mail, BellRing, FileUp, Loader2, CheckCircle2, AlertCircle } from 'lucide-react';
import { useStore } from '../lib/store';
import { Button } from '../components/ui/button';
import { Input } from '../components/ui/input';
import { Label } from '../components/ui/label';
import { Switch } from '../components/ui/switch';
import { extractBackupFromPDF, getReportPDFBase64 } from '../lib/pdf';
import { getAndroidBridgeOrNull } from '../components/PageTopBar';
import PageTopBar from '../components/PageTopBar';

function Section({ title, children }) {
  return (
    <div className="mt-6">
      <h2 className="px-1 text-[11px] uppercase tracking-wider font-semibold text-gray-500">{title}</h2>
      <div className="mt-2 bg-white rounded-2xl border border-gray-100 divide-y divide-gray-100 overflow-hidden">
        {children}
      </div>
    </div>
  );
}

function Row({ icon: Icon, title, subtitle, right, onClick }) {
  return (
    <button onClick={onClick} className="tap-row w-full flex items-center gap-3 px-4 py-3 text-left text-gray-900">
      <div className="w-9 h-9 rounded-lg flex items-center justify-center bg-teal-50 text-teal-600">
        <Icon size={18} />
      </div>
      <div className="flex-1 min-w-0">
        <div className="text-sm font-semibold">{title}</div>
        {subtitle && <div className="text-xs text-gray-500">{subtitle}</div>}
      </div>
      {right || <ChevronRight size={18} className="text-gray-300" />}
    </button>
  );
}

function formatLastBackup(iso) {
  if (!iso) return 'Never';
  try {
    const dt = new Date(iso);
    return dt.toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric' });
  } catch { return 'Never'; }
}

export default function Backup() {
  const { state, updateSettings, exportData, importData, markBackedUp } = useStore();
  const fileInputRef = useRef(null);
  const pdfImportRef = useRef(null);
  const [pdfImportStatus, setPdfImportStatus] = useState({ state: 'idle', message: '' }); // idle | busy | ok | error

  const triggerDownload = () => {
    const json = exportData();
    const stamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19);
    const fileName = `finance-buddy-backup-${stamp}.json`;

    const bridge = getAndroidBridgeOrNull();
    if (bridge && typeof bridge.saveJsonBackup === 'function') {
      // Native Android: write the JSON straight into the system Downloads
      // folder (Blob downloads are blocked inside file:// WebViews).
      bridge.saveJsonBackup(json, fileName);
      return;
    }

    // Web fallback: standard Blob download.
    const blob = new Blob([json], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = fileName;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const onExport = () => {
    try { triggerDownload(); markBackedUp(); }
    catch (e) { console.error(e); }
  };

  const onImportClick = () => fileInputRef.current?.click();

  const onFileChosen = async (e) => {
    const file = e.target.files?.[0];
    e.target.value = '';
    if (!file) return;
    try {
      const text = await file.text();
      importData(text);
    } catch (err) { console.error(err); }
  };

  const onEmailBackup = async () => {
    const email = state.settings?.autoBackupEmail || '';
    try {
      const stamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19);
      const jsonText = exportData();
      const jsonName = `finance-buddy-backup-${stamp}.json`;
      const pdfName = `finance-buddy-report-${stamp}.pdf`;

      const bridge = getAndroidBridgeOrNull();
      if (bridge && typeof bridge.emailBackup === 'function') {
        // Native Android: open the email composer with JSON + PDF attached.
        let pdfBase64 = '';
        try { pdfBase64 = await getReportPDFBase64({ state }); }
        catch (e) { console.warn('PDF generation failed for email', e); }
        bridge.emailBackup(jsonText, jsonName, pdfBase64, pdfName, email);
        markBackedUp();
        return;
      }

      // Web fallback: download the JSON locally and open the user's mail
      // client with mailto: so they can attach it manually.
      triggerDownload();
      markBackedUp();
      const subject = encodeURIComponent('Finance Buddy backup');
      const body = encodeURIComponent(
        'Attach the JSON file just downloaded to this email.\n\n' +
        'Generated by Finance Buddy on ' + new Date().toLocaleString() + '.'
      );
      const target = email ? `mailto:${encodeURIComponent(email)}` : 'mailto:';
      window.location.href = `${target}?subject=${subject}&body=${body}`;
    } catch (e) { console.error('Email backup failed', e); }
  };

  const onImportFromPDFClick = () => {
    setPdfImportStatus({ state: 'idle', message: '' });
    pdfImportRef.current?.click();
  };

  const onPDFImportFileChosen = async (e) => {
    const file = e.target.files?.[0];
    e.target.value = '';
    if (!file) return;
    setPdfImportStatus({ state: 'busy', message: 'Reading PDF…' });
    try {
      const json = await extractBackupFromPDF(file);
      if (!json) {
        setPdfImportStatus({
          state: 'error',
          message: 'No Finance Buddy data found in this PDF. Pick a PDF generated by this app.',
        });
        return;
      }
      importData(json);
      markBackedUp();
      setPdfImportStatus({ state: 'ok', message: 'Data restored from PDF.' });
    } catch (err) {
      console.error('Import from PDF failed', err);
      setPdfImportStatus({
        state: 'error',
        message: 'Could not import this PDF. The file may be damaged.',
      });
    }
  };

  const autoBackupEnabled = !!state.settings?.autoBackupEnabled;
  const autoBackupEmail = state.settings?.autoBackupEmail || '';
  const lastBackupAt = state.settings?.lastBackupAt;

  return (
    <div className="px-5 pt-4">
      <PageTopBar />
      <h1 className="mt-2 text-3xl font-extrabold tracking-tight text-gray-900">Backup</h1>
      <p className="text-sm text-gray-500 mt-1">Export, import and email your data — all stays on this device.</p>

      <Section title="Backup & Restore">
        <Row icon={Download} title="Export Backup" subtitle="Download all data as JSON file" onClick={onExport} />
        <Row icon={Upload} title="Import Backup" subtitle="Restore from a JSON file" onClick={onImportClick} />
        <input ref={fileInputRef} type="file" accept="application/json,.json" hidden onChange={onFileChosen} />

        <div className="px-4 py-3 flex items-center gap-3">
          <div className="w-9 h-9 rounded-lg bg-teal-50 text-teal-600 flex items-center justify-center"><BellRing size={18} /></div>
          <div className="flex-1 min-w-0">
            <div className="text-sm font-semibold text-gray-900">Auto-backup reminder</div>
            <div className="text-xs text-gray-500">Remind me every 7 days to back up</div>
          </div>
          <Switch
            checked={autoBackupEnabled}
            onCheckedChange={(v) => updateSettings({ autoBackupEnabled: !!v })}
          />
        </div>

        <div className="px-4 py-3 grid gap-2">
          <Label className="text-xs flex items-center gap-1.5 text-gray-500">
            <Mail size={12} /> Backup Email Address
          </Label>
          <Input
            type="email"
            inputMode="email"
            value={autoBackupEmail}
            onChange={(e) => updateSettings({ autoBackupEmail: e.target.value })}
            placeholder="you@example.com"
          />
          <Button onClick={onEmailBackup} className="bg-teal-600 hover:bg-teal-700 mt-1">
            <Mail size={16} className="mr-2" />
            Email Backup Now
          </Button>
          <p className="text-[11px] text-gray-400">
            Last backup: <span className="font-semibold text-gray-600">{formatLastBackup(lastBackupAt)}</span>
          </p>
        </div>

        <div className="px-4 py-3 grid gap-2">
          <Label className="text-xs flex items-center gap-1.5 text-gray-500">
            <FileUp size={12} /> Import from PDF
          </Label>
          <p className="text-[11px] text-gray-500">
            Pick a Finance Buddy report PDF previously generated by this app. Your data will be fully restored from the embedded backup.
          </p>
          <Button
            onClick={onImportFromPDFClick}
            disabled={pdfImportStatus.state === 'busy'}
            className="bg-teal-600 hover:bg-teal-700 mt-1 disabled:opacity-60"
            data-testid="import-from-pdf-btn"
          >
            {pdfImportStatus.state === 'busy' ? (
              <>
                <Loader2 size={16} className="mr-2 animate-spin" />
                Importing…
              </>
            ) : (
              <>
                <FileUp size={16} className="mr-2" />
                Import from PDF
              </>
            )}
          </Button>
          {pdfImportStatus.state === 'ok' && (
            <p className="mt-1 flex items-start gap-1.5 text-[11px] text-emerald-700" data-testid="import-from-pdf-status">
              <CheckCircle2 size={12} className="mt-[1px]" />
              <span>{pdfImportStatus.message}</span>
            </p>
          )}
          {pdfImportStatus.state === 'error' && (
            <p className="mt-1 flex items-start gap-1.5 text-[11px] text-rose-700" data-testid="import-from-pdf-status">
              <AlertCircle size={12} className="mt-[1px]" />
              <span>{pdfImportStatus.message}</span>
            </p>
          )}
          <input
            ref={pdfImportRef}
            type="file"
            accept="application/pdf,.pdf"
            hidden
            onChange={onPDFImportFileChosen}
          />
        </div>
      </Section>

      <p className="mt-6 mb-4 text-center text-[11px] text-gray-400">All your data stays on this device.</p>
    </div>
  );
}
